version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: webapp-frontend
    environment:
      - API_URL=http://backend:3001
    ports:
      - "3000:3000"  # Expose frontend on port 8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "start"]
    mem_reservation: 100m
    mem_limit: 512m

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: webapp-backend
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/webapp?user=webapp&password=secret
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
    command: ["npm", "run", "dev"]
    mem_reservation: 256m
    mem_limit: 512m

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=webapp
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    mem_reservation: 100m
    mem_limit: 200m
